services:
  vpr-service:
    container_name: vpr-service
    image: vpr-service
    build:
      context: ./vpr-service
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    hostname: vpr-service
    depends_on:
      - db
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB_VPR}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER_VPR}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD_VPR}
  db:
    container_name: postgresDB
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB_VPR}
      POSTGRES_USER: ${POSTGRES_USER_VPR}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_VPR}
#    volumes:
#      - db-data:/var/lib/postgresql/data
#      - ./vpr-service/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9093:9093"
    environment:
      KAFKA_KRAFT_MODE_ENABLED: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  audit-service:
    container_name: audit-service
    image: audit-service
    build:
      context: ./audit-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      SPRING_AUDIT_DATASOURCE_URL: jdbc:postgresql://audit-db:5432/${POSTGRES_DB_AUDIT}
      SPRING_AUDIT_DATASOURCE_USERNAME: ${POSTGRES_USER_AUDIT}
      SPRING_AUDIT_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD_AUDIT}
    depends_on:
      - kafka
      - audit-db
  audit-db:
    image: postgres:15
    container_name: audit-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB_AUDIT}
      POSTGRES_USER: ${POSTGRES_USER_AUDIT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUDIT}
    ports:
      - "5433:5432"
volumes:
  db-data: