services:
  application:
    container_name: vpr
    image: vpr
    build: .
    ports: [8081:8081]
    hostname: vpr
    depends_on:
      - db
  db:
    container_name: postgresDB
    image: postgres:13.3
    environment:
      POSTGRES_DB: "VPR"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1111"
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql